### ISSUE TITLE
[BUG] The JSON endpoint for tweets containing GIFs returns a HTTP 500 error

### ISSUE THREAD

**Issue by TheAppleFreak** [Twxtter/Twxtter-main#24]
**Describe the bug**
Tweets containing GIFs cause the JSON endpoint to return an internal server error (HTTP 500). 

**To Reproduce**
1. Find a tweet containing a GIF (for example, https://twitter.com/The_PinkPirate/status/1537915696822177793)
2. Change the host to Twxtter, and add `.json` to the end so it hits the JSON endpoint (https://twxtter.com/The_PinkPirate/status/1537915696822177793.json)

**Expected behavior**
A JSON payload to be returned containing the tweet information. 

**Additional notes**
Given as GIF tweets embed correctly within Discord, my initial guess would be that this is purely an issue with the JSON endpoint. Additionally, other forms of tweets, [like image posts,](https://twxtter.com/Bo_oj0916/status/1537827247360450561.json) work as expected.

**Comment by lyricalpaws** [comment]
Tracked down the issue, `UnboundLocalError: local variable 'url' referenced before assignment` around `line 614`, when I have a moment I'll see what I can do, unless someone else gets to it first

**Comment by lyricalpaws** [comment]
Fixed
