### ISSUE TITLE
[BUG] direct video links are broken

### ISSUE THREAD

**Issue by nanopone** [Twxtter/Twxtter-main#4]
**Describe the bug**
all of the methods of getting a direct mp4 from twitter are broken.

**To Reproduce**
1. use /dir/, /dl/ or d.twxtter.com
2. either nothing happens or theres a 500 error

**Expected behavior**
a direct downloadable video just like on fxtwitter

**Comment by lyricalpaws** [comment]
Should have been fixed in #5
